# 工作流名称
name: Build TV App APK

# 触发工作流的事件
on:
  # 当有代码推送到 main 分支时触发
  push:
    branches: [ "master" ]
    # (可选，但强烈推荐) 只有当 simple_live_tv_app 目录下的文件发生变化时才触发
    paths:
      - 'simple_live_tv_app/**'
      
  # 允许手动触发
  workflow_dispatch:

# 定义工作任务
jobs:
  build:
    # 指定运行环境
    runs-on: ubuntu-latest

    # 定义任务步骤
    steps:
      # 1. 检出代码：这一步不需要指定工作目录
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' 
          cache: true

      # 4. 获取 Flutter 依赖 (在 TV App 目录中执行)
      - name: Install dependencies
        # 新增：指定工作目录
        working-directory: ./simple_live_tv_app
        run: flutter pub get

      - name: Decode Keystore and Create Key Properties
        env:
          KEYSTORE_BASE64_SECRET: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "Creating keystore file..."
          echo "$KEYSTORE_BASE64_SECRET" | base64 --decode > android/app/upload-keystore.jks
          echo "Creating key.properties file..."
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties            

      # 5. 编译 Debug APK (在 TV App 目录中执行)
      - name: Build Release APK
        # 新增：指定工作目录
        working-directory: ./simple_live_tv_app
        run: flutter build apk --release

      # 6. 上传构建产物
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact 的名称
          name: tv-app-debug-apk
          # 要上传的文件的路径，必须从仓库根目录开始写
          path: simple_live_tv_app/build/app/outputs/flutter-apk/app-debug.apk
